### ISSUE TITLE
Can't retrieve current source from TV

### ISSUE THREAD

**Issue by O2-AC** [jaruba/ha-samsungtv-tizen#10]
First of all, thanks for this great component. It works very well so far. I am able to change between input sources via Home-Assistant, but if I do so the `source` state is not changed and remains TV/HDMI. If I use the Dashboard and select a source from the Dropdown menu the selected source is showing up for a short time and then the field gets emptied again. 
This makes it quit impossible to determine which source is currently selected and build automations based upon this trigger.
Did you observe similar behavior before? 
The TV in question is a Samsung UE40NU7189

**Comment by jaruba** [comment]
There is currently no known way of distinguishing between input sources. The states get updated only on TV App selections, as there is an API for that.

So you will get states for "Netflix", "YouTube", and all other TV Apps, but it will only show "TV/HDMI" if no TV App is currently running and visible.

**Comment by jaruba** [comment]
From some research though, I believe it may be possible to get input data from a TV by hooking up the RPI (if u are using one) to the TV directly and setting up HDMI CEC. I may be wrong though.. I can't vouch for anything until I see it working, and this is a far reached workaround anyway..

**Comment by O2-AC** [comment]
Thanks for looking into it so quickly. Hooking up an RPi directly to the TV is not really feasible in my scenario and as you said quite a far reached workaround. I will have to think how I can trigger automations when switching inputs then in another way. Maybe I'll use a smart switch to switch inputs instead of the Samsung Remote and therefore trigger an automation on changing the state of the smart switch. 
I guess, this could be closed then, since there's nothing else to be done with regard to your custom component :)

**Comment by jaruba** [comment]
I'll leave it open, maybe there will be some way to do it at some point, who knows..

**Comment by jaruba** [comment]
It seems there is a way to get the input, and set it correctly, etc.

But that would need to go through the SmartThings Cloud API, which I think is out of scope for this component.

There are more details in this issue thread: https://github.com/jaruba/ha-samsungtv-custom/issues/5

**Comment by O2-AC** [comment]
I see. Interesting that one needs the Cloud API to access this information. But I agree that such a solution is out of scope for this component. Thanks for the quick responses

**Comment by jaruba** [comment]
There might still be a local way too, but with so many undocumented local APIs on the Samsung TVs, it's like pinning the tail on the donkey.

**Comment by jaruba** [comment]
Newest release includes the SmartThings API, you'll need to set `api_key` and `device_id` to enable it. The SmartThings API adds many new things, and also fixes this issue.
