### ISSUE TITLE
struggle to rule the integration via code

### ISSUE THREAD

**Issue by Vooovan** [jaruba/ha-samsungtv-tizen#100]
Hello!
I use the integration at HA with gratitude
thank you

But 
need to write the script to go to browser web-page. can't do it
help please. 
didn't't find it in the description.

entity_id: media_player.samsung_tv_remote
media_content_type: "browser"
media_content_id: "https://www.yandex.ru"

<img width="634" alt="image" src="https://user-images.githubusercontent.com/67726392/100130222-8583a700-2e93-11eb-93c8-0e8dbace8a7c.png">

**Comment by Vooovan** [comment]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/67726392/100130366-ac41dd80-2e93-11eb-998b-8f72447bc9de.png">

**Comment by jaruba** [comment]
@Vooovan you are using the wrong service, it should be `media_player.play_media`, not `media_player.media_play`
