### ISSUE TITLE
Integration fails with simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by denysdovhan** [jaruba/ha-samsungtv-tizen#101]
I've just upgraded to v1.5.6 and got my TV unavailable with this message in my logs:

```
Logger: homeassistant.helpers.entity
Source: custom_components/samsungtv_tizen/smartthings.py:40
First occurred: 1:02:06 (18 occurrences)
Last logged: 1:06:24

Update for media_player.samsung_tv fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 424, in update
    smartthings.device_update(self)
  File "/config/custom_components/samsungtv_tizen/smartthings.py", line 40, in device_update
    data = resp.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Trying to get it working by rolling back to previous versions. I will be grateful for any tip to get it back working.

**Comment by jaruba** [comment]
@Screwdgeh oh boy, we broke it

**Comment by jaruba** [comment]
@denysdovhan what version were u previously using?

**Comment by jaruba** [comment]
@denysdovhan also, is there anything special about ur network setup? does HA have access to the internet?

**Comment by denysdovhan** [comment]
UPD: I rolled back to `v1.5.4` and it fails as well (I get the same error). It's strange because it seems to be working before.

I was using `1.5.4`. Yes HA has access to the internet since all of my other integrations work perfectly. I mean those integrations that require access to the outer world.

**Comment by jaruba** [comment]
we made an update that downloads the channel logo paths from an online source: https://jaruba.github.io/channel-logos/logo_paths.json

(where we keep the channel logo paths updated based on TMDB data + image post-processing)

before that we hardcoded the channel logo paths in a file with the component.

I think that v1.5.3 is pre-channel logos.. unless i'm wrong and this has nothing to do with channel logos.. did not check your logs thoroughly yet.

**Comment by jaruba** [comment]
wait.. this has nothing to do with the channel logos, you're getting an error from `smartthings.device_update(self)`

there's something wrong with the smartthings API for you.. check your smartthings credentials

**Comment by jaruba** [comment]
i think you can even update to the latest version again, but you need to try to reset your credentials from smartthings, there is a discussion here with various users that needed to reset smartthings due to different issues, maybe it can help you also: https://github.com/jaruba/ha-samsungtv-tizen/issues/77

**Comment by denysdovhan** [comment]
Yeah, that was a problem on my side. My TV had DNS wrong settings. It used to point to my AdGuard Home DNS which was blocking access to the Smart Things services.

**Comment by jaruba** [comment]
@denysdovhan I'm happy you got it working again, I'm also very happy that the channel logos feature wasn't to blame. 😅

**Comment by denysdovhan** [comment]
Thanks for pointing me in the right direction!
