### ISSUE TITLE
 Platform error media_player.samsungtv_tizen - No module named 'dateutil' - Version 2020.12.0

### ISSUE THREAD

**Issue by dsv591** [jaruba/ha-samsungtv-tizen#105]
Config validation on version 2020.12.0 is failing with

Testing configuration at /tmp/config
Failed config
  General Errors: 
    - Platform error media_player.samsungtv_tizen - No module named 'dateutil'

**Comment by profx5015** [comment]
Got the same issue
Is there any solution?

**Comment by Screwdgeh** [comment]
Both, I think this was due to an undeclared dependency on that module within the custom component! A change was just committed to remove dependency on this module as it wasn't really needed, can you please download the custom_component files again and see if the change fixes your issue?

**Comment by dsv591** [comment]
It's fixed! Thanks!

**Comment by jaruba** [comment]
I made a new release with the changes: v1.5.7

It should be available as an update in HACS now
