### ISSUE TITLE
problem with Homekit integration

### ISSUE THREAD

**Issue by pilot1981** [jaruba/ha-samsungtv-tizen#107]
Hi,
I have HASSIO 2020.12.1 installed on Rpi3b+, your component work fine with my TV.

I notice, when I go to activate homekit integration I have some problem:

if I integrate in homekit climate and vacuum, all works fine; when I go to add your media_player, all HA items disappear from homekit (media_player, climate and vacuum).

Your component is compatible with homekit integration of HA?

any idea?

can you give me any suggestion to troubleshoot this behaviour?

**Comment by pilot1981** [comment]
I also tried disabling attribute channel_list and app_list but problem remain there.

Here is may config in configuration.yaml:

media_player:
  - platform: samsungtv_tizen
    name: TV
#    app_list: '{"Netflix": "11101200001", "YouTube": "111299001912"}'
    host: 192.168.4.151
    mac: "a4:30:7a:e7:7a:f0"
    port: 8002
#    channel_list: '{"RAI1": "1", "RAI2": "2", "RAI3": "3", "RETE4": "4", "CANALE5": "5", "ITALIA1": "6"}'
    is_frame_tv: true
    api_key: "98529d37-xxxxxxxxxxxxxx-7fbf073eb0a6"
    device_id: "1362c781-xxxxxxxxxxxxx-3931eb8366b0"

**Comment by jaruba** [comment]
I haven't heard much from homekit users, but this other post seems to suggest it works: https://github.com/jaruba/ha-samsungtv-tizen/issues/89

The only thing this component does is identify itself as a Smart TV, respecting the expectations from such a device, the actual communication and exposing of devices is done by HA. So I think it's much more probable that this is a HA or Homekit issue..

Google Assistant and Alexa are documented, so this works with other assistants for sure.

**Comment by pilot1981** [comment]
I think the problem appeared in last 1 or 2 months of versions...what you suggest? I can open an issue on GitHub of HA? also if this component isn't officially supported?

**Comment by jaruba** [comment]
I wouldn't know what to suggest.. I can only tell u that I don't think the component is at fault, u should check ur HA logs, it might offer more clues.

I don't use homekit, so I can't test this myself.

**Comment by pilot1981** [comment]
thanks. I can replicate problem so I can try with logs...

I searched in /config/home-assistant.log file but nothing useful...I have to search in some other files?

First I have to change debug level in configuration yaml? you can give me some suggestion, please?

**Comment by pilot1981** [comment]
OK, I think I found solution to my problem.

I gone to developer tools->services

called homekit.reset_accessory service on entity media_player.tv

and then all worked fine! Now TV is visibile also in homekit: wonderful!


I have Frame 2020 TV, you plan to support art mode, or you suggest me to migrate to component https://github.com/ollo69/ha-samsungtv-smart?

**Comment by jaruba** [comment]
You can track this issue for improved art mode support: https://github.com/jaruba/ha-samsungtv-tizen/issues/106

I'll close this issue as it has been resolved.

**Comment by pilot1981** [comment]
Problem appeared again...

**Comment by jaruba** [comment]
Given the way u fixed it, u should now be aware that this cannot be this component's fault..

**Comment by pilot1981** [comment]
I’m not sure...

**Comment by pilot1981** [comment]
I installed custom components of ollo69 and it works fine in homekit...always media_player type...

https://github.com/ollo69/ha-samsungtv-smart/

it also works with art mode...

thanks for your job, I respect your job! but...
