### ISSUE TITLE
Notification on TV ?

### ISSUE THREAD

**Issue by B0ndo2** [jaruba/ha-samsungtv-tizen#110]
Is there a way to send notification to the TV ?. I want to show a notification when someone is at the door, sort of a pop up ?

**Comment by jaruba** [comment]
No, but u can open a browser page on the TV, or tell it to play a video. I know at least one user that wanted to send the smart doorbell feed to the TV when someone was at the door, not sure if he ever succeeded.

**Comment by B0ndo2** [comment]
I was able to pay mp3 file from a local web server for that but was looking
for notifications as it is available in LG
