### ISSUE TITLE
solved: HDMI list not appearing on my smart tv with api key

### ISSUE THREAD

**Issue by fusionstream** [jaruba/ha-samsungtv-tizen#114]
TV state shows "TV/HDMI" and selection only allows "TV" and "HDMI" despite api_key and device_id being set. You need to manually list the HDMI channels in source_list for it to appear correctly. I don't know why this is the case. Just putting it out there.

**Comment by jaruba** [comment]
@fusionstream This has always been the case, the component can grab the `app_list` itself in some scenarios, but not the `source_list`.

**Comment by fusionstream** [comment]
No worries. I didn't see it in the docs so figured I'd post. Unless I missed it. :)
