### ISSUE TITLE
Asia Pacific/Australia shard missing but ...

### ISSUE THREAD

**Issue by jeffgoh** [jaruba/ha-samsungtv-tizen#119]
allegedly, it should auto-detect for all regions.  Worked for me. YMMV.

https://community.smartthings.com/t/faq-how-to-find-out-what-shard-cloud-slice-ide-url-your-account-location-is-on/53923

Mine turned out to be : https://graph-ap02-apnortheast2.api.smartthings.com/ - which presumably is in AWS Seoul.

This is for : https://github.com/jaruba/ha-samsungtv-tizen/blob/master/Smartthings.md#smartthings-keys

**Comment by Screwdgeh** [comment]
Clarified this inside smartthings.md, thanks for helping with this!
