### ISSUE TITLE
REQUEST: Broadcast Address Config Variable

### ISSUE THREAD

**Issue by alxscott** [jaruba/ha-samsungtv-tizen#12]
Hi,

Firstly Thank You for a fantastic improvement over the stock integration.

Unfortunately due to my home wifi / network setup my TV and HA are on different subnets. With the original Integration WOL worked when the subnet was given; but when I try to add this to yours I get a incorrect config error.

Can I request an option to config a broadcast address for the WOL packet?

Thank you!

**Comment by jaruba** [comment]
Sorry for the late reply, I'll have to dig into the official component to see what it does with the subnet. Unfortunately, I can't give an estimate in time as this is not really a priority for this component right now.

**Comment by jaruba** [comment]
`broadcast_address` has been added to the latest release
