### ISSUE TITLE
getcurrentchannel

### ISSUE THREAD

**Issue by randompee** [jaruba/ha-samsungtv-tizen#120]
I use your integration only when I am away on holiday, to give the impression of someone using the TV. That works great, even when the WOL not always starts the device; but then the ON/OFF button works as fallback (I control the state via webcam). Very nice work, thank you!

What I would like to see is integration of the function "getcurrentchannel". The reason is that it would then be easy to see wheather I already have the desired TV channel or should change it. Don't know if it is o.k. to post a feature request here or not, if not, I apologize...

**Comment by Screwdgeh** [comment]
Hello @randompee,

The current TV channel is shown as media title when the smartthings API is enabled (see instructions here: https://github.com/jaruba/ha-samsungtv-tizen/blob/master/Smartthings.md). Note that this only works for regular internally decoded cable/antenna TV channels and not for live TV via external devices. It can be read programmatically from the media player entity as 'media_title' state attribute.
