### ISSUE TITLE
No version key in the manifest file

### ISSUE THREAD

**Issue by matt8707** [jaruba/ha-samsungtv-tizen#130]
Home Assistant 2021.3.0b3 log

No 'version' key in the manifest file for custom integration 'samsungtv_tizen'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'samsungtv_tizen'

**Comment by avbor** [comment]
+1

**Comment by TEO984** [comment]
+1

**Comment by kreene1987** [comment]
+2

**Comment by kornelremete** [comment]
+3

**Comment by jaruba** [comment]
We are currently on the verge of a new major release which will be a radical change for this component, if that gets delayed more I will make a release just for adding the version key.
