### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'samsungtv_tizen'.

### ISSUE THREAD

**Issue by HausnerA** [jaruba/ha-samsungtv-tizen#137]
No 'version' key in the manifest file for custom integration 'samsungtv_tizen'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'samsungtv_tizen'

**Comment by timborino** [comment]
Some more details from the HA release notes:

> **[Custom integrations: Version warning](https://www.home-assistant.io/blog/2021/04/07/release-20214/#breaking-changes)**
> Custom integrations now require a version key in their manifest file, this also means that all custom integrations now require a manifest file.
> 
> If you are using a legacy custom integration like _custom_components/awesome.py_ this now needs to move to _custom_components/awesome/__init__.py_ so you can add _custom_components/awesome/manifest.json_ to it.
> 
> For more information about integration, manifests have a look here: https://developers.home-assistant.io/docs/creating_integration_manifest
> 
> For now, this will create a warning on startup. But this will be blocked from loading if it’s missing a version in the manifest starting with Home Assistant 2021.6.
> 
> If you see these warnings, please report the issue with the author of that custom integration.

**Comment by Smiley-94** [comment]
you can modify:
  "homeassistant": "0.99.3"
  
 into: 
   "homeassistant": "0.99.3",
  "version": "1.5.7"
  
at the end of the file: /config/custom_components/samsungtv_tizen/manifest.json

then reboot and the problem will be solved, they are planning to update the component soon adding this too, for now this is the solution

**Comment by jaruba** [comment]
Made a new release and added the version key to it.
