### ISSUE TITLE
controls not working

### ISSUE THREAD

**Issue by dataegg** [jaruba/ha-samsungtv-tizen#159]
I have a Samsung UE48J5500 and information is recieved by home assistant, 

I can see things like volume level, if tv is on etc but I'm not able to send commands. I never got a pop up on the TV but it is not blocked
I'm using wireless interface and TV is in same subnet/vlan?

Anybody any suggestions?

Regards,
Martin

Info visible in HA developer tools

source_list: TV, HDMI
volume_level: 0.06
is_volume_muted: false
media_title: TV/HDMI
source: TV/HDMI
friendly_name: Samsung TV Remote
supported_features: 20413
device_class: tv

This is the info from my TV when accessing via browser.

{
  "id": "uuid:901a7147-04e5-4f19-802c-6d2240560ca1",
  "name": "[TV] Woonkamer",
  "version": "2.0.25",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "uuid:901a7147-04e5-4f19-802c-6d2240560ca1",
    "model": "15_HAWKM_2D",
    "modelName": "UE48J5500",
    "description": "Samsung DTV RCR",
    "networkType": "wireless",
    "ssid": "3c:37:12:2c:f3:f8",
    "ip": "172.29.101.31",
    "firmwareVersion": "Unknown",
    "name": "[TV] Woonkamer",
    "id": "uuid:901a7147-04e5-4f19-802c-6d2240560ca1",
    "udn": "uuid:901a7147-04e5-4f19-802c-6d2240560ca1",
    "resolution": "1920x1080",
    "countryCode": "NL",
    "msfVersion": "2.0.25",
    "smartHubAgreement": "true",
    "wifiMac": "78:BD:BC:28:D1:E5",
    "developerMode": "0",
    "developerIP": ""
  },
  "type": "Samsung SmartTV",
  "uri": "http://172.29.101.31:8001/api/v2/"
}

**Comment by dataegg** [comment]
I wrote the TV is on the same subnet/vlan as Home Assistant but thats not fully true, I'm running a container in podman and bridged networking is used and this could be my issue. I'll try another networking type at which home assistant will be on the same network.

I will report my findings here

**Comment by AKuHAK** [comment]
@dataegg J5500 is not from the `Tizen` family, it is from the `encrypted` family. Take a look at https://github.com/sermayoral/ha-samsungtv-encrypted

**Comment by dataegg** [comment]
@AKuHAK Thanks for your response and I'm happy to try encrypted but when I google for specs I find on several places it has Tizen OS, for example here: https://www.displayspecifications.com/en/model/f790a1

Are you sure I need the encrypted version?

**Comment by AKuHAK** [comment]
@dataegg yes, you are correct, you have Tizen. Here is [the list](https://developer.samsung.com/smarttv/develop/specifications/tv-model-groups.html) BTW.

**Comment by dataegg** [comment]
@AKuHAK ok thanks for the list. I'll continue to put the podman/docker container in the same network as the TV bu I found out the macvlan support on podman is deprecated so I guess I need something else but I'm quite new to podman so I have to figure out how to do this.

**Comment by dataegg** [comment]
I now have my homeassistant container in the same network as the tv. The TV is discovered automatically by home assistant but no pop up is shown on the tv screen to allow access and I'm still unable to control it. Could it be my tv is to old (2015 model)?

**Comment by dataegg** [comment]
In the meanwhile I tried all samsung smart tv integration available 

samsung TV tizen (this integration)
samsung tv smart
ha samsungtv custom
samsungtv encrypted

unfortunately none of the integrations seem to work fully. I can get info from the TV but I can't control the TV

If anybody has a working configuration with J5500 I am very interested.
