### ISSUE TITLE
TV showing as on, even when ping fails

### ISSUE THREAD

**Issue by parampatwala** [jaruba/ha-samsungtv-tizen#16]
The media player component shows the TV as ON/unavailable shortly after pressing the off button (Goes to off for 10-30 seconds and then the state changes back to on/unavailable, even through the TV is off and the ping is unreachable from my laptop)

I have a UA55NU7100 (2018)

My config:
`  - platform: samsungtv_custom
    host: 192.168.1.38
    port: 8002
    mac: XXX
    app_list: '{"Netflix": "11101200001", "YouTube": "111299001912", "Spotify": "3201606009684"}'`

**Comment by jaruba** [comment]
@parampatwala set `update_method: "ping"` in your config if you want it to rely on ping to see if the TV is on or off.

**Comment by parampatwala** [comment]
Thanks, that did mostly solve it - the network interface seems to stay online for 4-5 minutes after it powers on.

What does the default update method do? Is there a way to use that while ensuring the power state works as well?

**Comment by jaruba** [comment]
@parampatwala 

The default method sends `KEY` to the WebSocket server to see if it's alive. The ping method is better imo, there is no way of making any of these 2 update methods more accurate then they are.

**Comment by jaruba** [comment]
Newest release includes the SmartThings API, you'll need to set `api_key` and `device_id` to enable it. The SmartThings API adds many new things, and also fixes this issue.
