### ISSUE TITLE
Restart HA when TV powered off...

### ISSUE THREAD

**Issue by avbor** [jaruba/ha-samsungtv-tizen#26]
Restart HA when TV powered off generate a lot of errors socket.timeout: timed out in log:
![image](https://user-images.githubusercontent.com/32452033/75674293-d7492900-5c95-11ea-9abb-50cac1b5334f.png)

![image](https://user-images.githubusercontent.com/32452033/75674313-ddd7a080-5c95-11ea-8053-5c90afe523fc.png)
Is any way to suppress this errors?

**Comment by jaruba** [comment]
set `app_list` in your config as described in the readme

**Comment by jaruba** [comment]
i think i have a solution for the issue, but it won't be available until next release, setting the `app_list` manually should make it go away though.

**Comment by avbor** [comment]
Thx, it works. But the automatic list of applications is much more convenient =)

**Comment by jaruba** [comment]
The new version should handle getting the `app_list` a bit better, but I still recommend setting it manually for best performance.
