### ISSUE TITLE
ST_HDMI1 command

### ISSUE THREAD

**Issue by madspeed** [jaruba/ha-samsungtv-tizen#27]
Hi!
I manage to control the TV, everything works fine, except for the cloud commands - ST_HDMI1, ST_HDMI2, ST_HDMI3
What may be wrong?
Config:

> 
media_player:
  - platform: samsungtv_tizen
    host: 10.4.3.119
    port: 8002
    mac: 00:c3:f4:20:74:62
    source_list: '{"TV": "KEY_TV", "HDMI": "KEY_HDMI", "TEST": "ST_HDMI2"}'
    api_key: 'a3045299-f3a3-4b7e-    -'
    device_id: '8a6d5331-a085-48df-    -'

**Comment by jaruba** [comment]
pleasw remove ur api key and device id from the comment, they are a security issue

**Comment by madspeed** [comment]
I have parcially removed them

**Comment by jaruba** [comment]
ok, good. can u check if u have any error? the ST_ keys should work as long as the smartthings api key and device id are correct..

Can you try more ST_ keys? like ST_TV and ST_HDMI1?

**Comment by madspeed** [comment]
Update for media_player.samsung_tv_remote fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/samsungtv_tizen/media_player.py", line 260, in update
    smartthings.device_update(self)
  File "/config/custom_components/samsungtv_tizen/smartthings.py", line 37, in device_update
    data = resp.json()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jaruba** [comment]
That error says that the api key and/or device id is wrong. Try without quotes, or try generating a new key, and double check if they were copied correctly.

**Comment by madspeed** [comment]
If i compltely remove api_key: and device_id: list of apps also disappears. If I return them back to config, list of apps returnes to sources list. Therefore I assume that HA gets connection to ST Cloud.
I can switch the apps easely, but HDMI inputs do not switch

**Comment by madspeed** [comment]
It is also interesting that if I add api key and device list, "KEY_TV" also stops working

**Comment by jaruba** [comment]
That may be a wrong assumption, I still think ur api key and/or device id may be incorrect.

**Comment by monsterciattolo** [comment]
I have the same problem.
in my config i generated the token on smartthing website and i use as api_key. is it correct?
I don't understand if api_key and device_id must be between "" or '' or nothing. Any help?

**Comment by monsterciattolo** [comment]
and finally i get the solution. i used the wrong device_id.
I used the Device Network Id instead device_id (nameid di: in current state)
I find the identificator in smartthing website - my devices - select device name on the first colum - find di: in current states

**Comment by madspeed** [comment]
> and finally i get the solution. i used the wrong device_id.
> I used the Device Network Id instead device_id (nameid di: in current state)
> I find the identificator in smartthing website - my devices - select device name on the first colum - find di: in current states

Thank you! I had exactly the same problem!

**Comment by jaruba** [comment]
@madspeed i told you the api key and/or device id were wrong..
