### ISSUE TITLE
keeps asking authorization with popup

### ISSUE THREAD

**Issue by wergio** [jaruba/ha-samsungtv-tizen#28]
tv model: UE43RU7170U
with latest update keeps asking authorization with popup on TV on every send_key and nothing happens, before this update was working.

in custom_components/samsungtv_tizen/ the file token-192.168.1.20.txt is empty. i tryed to delete but is recreated empty when popup appear on tv

api_key and device_id are correctly set. if i switch with remote from HDMI to TV I can see the media titles change in the lovelace card

I could swear the absolute first time i tryed to change the source from HDMI to TV worked, but after that after than and after many HASSIO reboot il couldn't do that again...

**Comment by jaruba** [comment]
many pop-ups are common, i've had that with previous versions too. how do u try changing from HDMI to TV?

**Comment by wergio** [comment]
now is working! I swear I tryed almost 10/15 times without success before posting... I was trying to switch source via lovelace card, and sending keys with developer tools->services

I kept trying some other times and now is working (pin now is correctly set in token-192.168.1.20.txt file). now source switch and keys are working (also key chaining). but ST_HDMI2 doesn't work (as before, at least for me)

I think I also changed
General > External Device Manager > Device Connection Manager
to "off" and then againt to "only first time", don't know if that helped...

**Comment by monsterciattolo** [comment]
What pin are you talking about? I have the same problem and my token file is empty

**Comment by wergio** [comment]
in /config/custom_components/samsungtv_tizen/token-<YOUR IP>.txt shoud be stored a pin number. Keept trying switching source from lovelace media player card, after MANY tryes worked for me. 
Also try to change to to "off" and then again to "only first time" the setting in General > External Device Manager > Device Connection Manager

**Comment by jaruba** [comment]
you just need to be patient. don't obsess over the pop up.

**Comment by monsterciattolo** [comment]
i got the pin! thanks

**Comment by jaruba** [comment]
I've made a new release that should fix getting the token from the pop-up.
