### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by Stooovie** [jaruba/ha-samsungtv-tizen#30]
Script doesn't work:

`'1583322636490':
  alias: Play PS4
  sequence:
  - data:
      entity_id: media_player.samsung_tv_remote
      media_content_id: ST_HDMI1
      media_content_type: send_key
    service: media_player.turn_on
  - entity_id: media_player.playstation_4
    service: media_player.turn_on`

(pastebin link [here](https://pastebin.com/wjSDSBmx))

Error:
`Failed to call service script/1583322636490. extra keys not allowed @ data['media_content_id']`

(No idea why the script is formatted like this and not as code but the indentations seem to be correct. The quotation marks from "send_key" and "ST_HDMI1" were removed by the HA script UI)

**Comment by jaruba** [comment]
You're right, I forgot to add support for key chaining and smartthings keys to the `play_media` service. It's a simple fix though, I made a new release, try it out.

**Comment by jaruba** [comment]
And your code should use `service: media_player.play_media` to send keys, not the `.turn_on` method.

**Comment by Stooovie** [comment]
Solved and donated. Thanks!
