### ISSUE TITLE
Media player showing "id"+ appname?

### ISSUE THREAD

**Issue by mike9011** [jaruba/ha-samsungtv-tizen#31]
# Issue
In some cases, when the app is started from the TV it has a id + app name in the mediaplayer:
![image](https://user-images.githubusercontent.com/18025163/75897359-b8cf6300-5e38-11ea-99b5-a2ad2e6c6c22.png)

When i open the card for more details, it's showing the correct source with the ID.
![image](https://user-images.githubusercontent.com/18025163/75897252-92a9c300-5e38-11ea-99fc-c97a732a907d.png)

My configuration:
`    app_list: '{"YouTube": "111299001912", "Netflix": "11101200001", "Plex": "3201512006963", "Videoland": "3201810017074"}'
`

Did i do something wrong, or is this a bug?

# System

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | Europe/Amsterdam
version | 0.106.5
virtualenv | false

Samsung TV Tizen  v1.4.1

**Comment by simoa** [comment]
@mike9011 Hi Mike, Can you please give me the apps ids of kpn and nlziet if possible ? Thanks very much
