### ISSUE TITLE
Cannot use entity for automation

### ISSUE THREAD

**Issue by markozekic** [jaruba/ha-samsungtv-tizen#39]
Hello,

 at first, thank you for your work!

I added it to my HA through HACS. But I cannot use entity for automation - for example I want to turn on light behind my screen when TV is on. But I cannot do this, because TV is added only as entity, not as device.

Is it a solution for this?

Thanks 

Marko

**Comment by jaruba** [comment]
> But I cannot do this, because TV is added only as entity, not as device.

Can you expand on this? What exactly is "a device" in your view.

Afaik all entities are devices, the entities created by this component are declared as `DEVICE_CLASS_TV`

**Comment by markozekic** [comment]
I am pretty new on this, so sorry for my maybe silly questions. 

this is my automation - I know there is a mistake in trigger, but dont know how to fix it:

- id: '1584471173953'
  alias: Svetlo u telky
  description: ''
  trigger:
  - entity_id: media_player.telka # telka is name from config
    from: '0'
    platform: state
    to: '1'
  condition:
  - after: sunset
    condition: sun
  action:
  - device_id: fd39def528be4708xxxxxxxxxxxx
    domain: switch
    entity_id: switch.zasuvka_tradfri_01_switch
    type: turn_on

Thank you for help.

Marko

**Comment by jaruba** [comment]
i think it should be:
```
  - entity_id: media_player.telka
    from: 'off'
    platform: state
    to: 'on'
```

**Comment by markozekic** [comment]
Simply :-).
It works.
Thank you!

**Comment by jaruba** [comment]
Happy to hear it.
