### ISSUE TITLE
HA still asking for permission at TV

### ISSUE THREAD

**Issue by markozekic** [jaruba/ha-samsungtv-tizen#40]
Hello,

 after HA update my TV still shows dialogue about HA wants to get permission every time I start TV.

Is it on my side or is it a bug?

Thank you

Marko

**Comment by jaruba** [comment]
I haven't updated HA yet, and it might take some time until I do. Theoretically, the only reason this could happen is if the token file is not saved, updating HA should not cause issues with this, although I could be wrong..

**Comment by zbeky** [comment]
Sometimes after reboot or component update I have persistent permission notification. No matter how many times I allow access, it pops again when I do any action from HA. The fix for me is to manually delete the token file. After this it catches in few tries.

Do you think it would be possible to delete the token file automatically after for example 10 unsuccessful authorization requests?

**Comment by jaruba** [comment]
@zbeky I would prefer finding and fixing the issues that is causing this for you. Are you sure you're using the latest version of this component? I already fixed a similar issue not too long ago.

**Comment by zbeky** [comment]
I am using 1.4.5 at the moment. Could update to 1.4.6 but commits in the latest release should not change anything in this regard

**Comment by colethegamer123** [comment]
I get the same error always, until I does not accept the permission Its not working properly. I get it everytime when I start the TV. I have the newest version and setuped correctly as I know.

**Comment by markozekic** [comment]
Same here - last update of both - HA and component. Mayby is the solution to add manually created longlife token to config?

**Comment by phrfpeixoto** [comment]
This started happening here too. Every single action in HA triggers a permission on the TV, and no longer works. =(

**Comment by phrfpeixoto** [comment]
> Sometimes after reboot or component update I have persistent permission notification. No matter how many times I allow access, it pops again when I do any action from HA. The fix for me is to manually delete the token file. After this it catches in few tries.
> 
> Do you think it would be possible to delete the token file automatically after for example 10 unsuccessful authorization requests?

How do you do that?

**Comment by markozekic** [comment]
This problem still persist. Is there any solution?

**Comment by phrfpeixoto** [comment]
I had it working back after deleting all permissions on the TV and rebooting HA.

**Comment by kdosiodjinud** [comment]
I have the same problem :-(

**Comment by alexintras** [comment]
same problem...

**Comment by jackm96** [comment]
same problem here

**Comment by jaruba** [comment]
I think i fixed this with v1.5.0, it should not show the authorization pop-up more then 2 times now. If it fails the first authorization it will increase the timeout for the second one to ensure it catches the token.

**Comment by jalada** [comment]
I also found removing all permissions on the TV seemed to help with this.
