### ISSUE TITLE
Mimic STB POWER key?

### ISSUE THREAD

**Issue by PDekker** [jaruba/ha-samsungtv-tizen#42]
Hello,

Loving your component. Everything is working fine and the smartthings addition really works great.

I’ve tried every possible key is the list, but I can’t seem to find the right one to power toggle my KPN STB box.

My Samsung Q9F does have the option to do thing. Pressing the KEY_MORE two times, KEY_ENTER and then use the left option in below screenshot

![5E689D13-65C3-4BB0-B961-CBF5A68458C7](https://user-images.githubusercontent.com/1951545/77170656-a6e9f300-6abb-11ea-973c-7657ad935a4f.jpeg)

I’d love to create an automation in Homeassistant to powertoggle the STB when the Samsung tv turns on. All other keys, like chup, chdown are correctly picked trough to the STB (wich is already great)

**Comment by jaruba** [comment]
Can't you use the key chaining feature for this? Something like:
`KEY_MORE+KEY_MORE+KEY_ENTER+KEY_LEFT+KEY_LEFT+KEY_ENTER`

**Comment by jaruba** [comment]
I presume my suggestion fixed your issue? Given the lack of response I will close this issue, if you consider it is still a problem you can reopen it.
