### ISSUE TITLE
YouTube TV App ID

### ISSUE THREAD

**Issue by rps-repo** [jaruba/ha-samsungtv-tizen#47]
Any idea what the app id for YouTube TV is?

**Comment by jaruba** [comment]
It's in the `app_list` docs, there are lists of app IDs linked there.

**Comment by rps-repo** [comment]
I only see YouTube in the lists and cannot find anything for YouTube TV.  These are two different apps.

**Comment by jaruba** [comment]
In the docs it also says:

> Another way of finding the alphanumerical ID is by enabling the [SmartThings API](https://github.com/jaruba/ha-samsungtv-tizen/blob/master/Smartthings.md) and running an app on the TV, this will show the alphanumerical ID as `media_title` in the component

**Comment by rps-repo** [comment]
Thanks for your help!  The app id for YouTube TV is PvWgqxV3Xa.YouTubeTV if anyone else is looking for it.
