### ISSUE TITLE
ue48ju7500

### ISSUE THREAD

**Issue by matteos1** [jaruba/ha-samsungtv-tizen#48]
with this series and with this configuration not work:
  - platform: samsungtv_tizen
    host: 192.168.1.13
    port: 8001
    mac: 24:4B:03:C9:C6:91

**Comment by jaruba** [comment]
The J in your TV's model number means that the TV was produced in 2015. In the documentation of this component it clearly states that only works with 2016+ Samsung TVs.

**Comment by matteos1** [comment]
ok thank you

**Comment by jaruba** [comment]
Np, and sorry, but supporting older TVs will complicate the logic of this component a lot, we need to work towards the future of Samsung TVs, not the past..

**Comment by matteos1** [comment]
:(
