### ISSUE TITLE
Plugin not powering off the TV

### ISSUE THREAD

**Issue by phoniclynx** [jaruba/ha-samsungtv-tizen#53]
After the last few updates of HA the plugin is no longer powering off the TV. Used to work fine until now.

**Comment by sh4rkt3ch** [comment]
Same here:

Addon : v1.4.6
HAC : 0.107.7
HASSOS : 3.12
Supervisor : 216

**Comment by jaruba** [comment]
have u tried to disable the default samsung component of the new HA versions?

**Comment by phoniclynx** [comment]
It says "Aborted - This Samsung TV device is currently not supported."

**Comment by sanderlv** [comment]
Hi have a samsumg led tv. Using port 8002 gives me an error, I can open port 8001 via browser and get "these are not the steroids your looking for". TV status is on in ha but I cannot control anything from there. I removed the integration autodiscovered component and the ha sees the tv upon restart. Cant control tv there as well. What could be wrong?

**Comment by sh4rkt3ch** [comment]
Jaruba - Sorry for the late reply, i cant see anywhere to disable the Samsung integration hassio comes with. Can you help

Thanks

**Comment by jaruba** [comment]
Sorry for being inactive lately. I've made an announcement [here](https://community.home-assistant.io/t/improving-samsung-tv-control/151922/230?u=jaruba).

**Comment by jaruba** [comment]
I think it's pretty clear that this ticket was created due to the confusion between this component and the official HA component, closing.
