### ISSUE TITLE
Samsung QE75Q7FN: lost entity whe HA Reboot

### ISSUE THREAD

**Issue by FilippoS1973** [jaruba/ha-samsungtv-tizen#61]
I would like to report this problem:
When HA restarts and the TV is turned off, the entity is lost
If the TV is turned on and HA starts up again everything works.
The problem arose after updating to HA 108.

this is my confguration:
- platform: samsungtv_tizen
    name: Samsung TV Q75
    host: samsungTV_ip
    port: 8002
    mac: samsungTV_MAC
    api_key: "my_API_KEY"
    device_id: "MY_DEVICE_ID"
    source_list: '{"TV": "ST_TV", "1": "ST_HDMI1", "Decoder 1": "ST_HDMI3", "LG Blu-Ray": "ST_HDMI4"}'
    update_method: "smartthings"

**Comment by jaruba** [comment]
set `app_list` manually as explained in the readme

**Comment by damianpasek** [comment]
I've got  a similar problem with losing entity. If TV is turned off and Home Assistant will reboot then the entity is not found. If I will turn on TV and reboot HA then entity is once again found and working. Any idea how to fix it? Here is my configuration: 

```
media_player:
  - platform: samsungtv_tizen
    host: IP
    port: 8002
    mac: "MAC_ADDRESS"
```

**Comment by FilippoS1973** [comment]
Problem resolved with HA 110 without any additional action
