### ISSUE TITLE
media_title issue

### ISSUE THREAD

**Issue by FilippoS1973** [jaruba/ha-samsungtv-tizen#66]
Media_ title no longer updates.
For some days I had always seen the same.
I also tried updating Smartthings. The first time the current media_title appears, it will never change again.
Has anything changed in the smartthings API?

**Comment by jaruba** [comment]
Sorry for being inactive lately. I've made an announcement [here](https://community.home-assistant.io/t/improving-samsung-tv-control/151922/230?u=jaruba).

**Comment by Kanishkaz** [comment]
I have this same issue. It looks like something has changed in the smarththings api. When you look at the smarthings api console, the data is the same.

**Comment by jaruba** [comment]
SmartThings definitely changed something, I believe there might be a way to fix this though by forcing it to update the channel names, but it could take a while to find the necessary time to reverse engineer it.

**Comment by Kanishkaz** [comment]
That would be great. Thank you for your efforts.
I can still see the media information correctly updating in the Smartthings iOS App. So the TV is definitely reporting channel info to it. But can't seem to access this info from the API.

**Comment by jaruba** [comment]
Yeah, it's obvious that Samsung stopped reporting this data in real time, which makes sense. I'm presuming that the app is now pinging the server to request this data on demand only when the app is active.

**Comment by josiamichael** [comment]
I also encountered the same problem as which the media_title is not updated in real time, but I also enountered the problem where i can't change my media source. Is this also an ongoing problem ?

**Comment by Kanishkaz** [comment]
Not sure if Samsung have fixed their API, but My tv channel info is updating correctly again. Will keep an eye on it.

**Comment by jaruba** [comment]
@Kanishkaz lol

**Comment by jaruba** [comment]
Yup, it works for me too again

**Comment by FilippoS1973** [comment]
Perfect! It works for me too.

**Comment by FilippoS1973** [comment]
Not sure but issue resolved as a result of the publication of Samsung's new privacy rules
