### ISSUE TITLE
Source not updating and selecting source not working correctly.

### ISSUE THREAD

**Issue by mike9011** [jaruba/ha-samsungtv-tizen#77]
Since the latest update of Home Assistant, the source of the Samsung TV isn't updated anymore.
When i manually pick a source, the source is changed on the TV, but it directly shows the TV is off in Home Assistant.

Edit; same issue with changing the volume up/down & mute. Reinstalled the component and gave permissions. 
Reboot HA & Samsung TV

**Recording:**
https://drive.google.com/file/d/1loI9__-mcB1938te792eDCIooN8Ktbjd/view?usp=sharing

**Configuration:**
 - platform: samsungtv_tizen
    host: 192.168.178.10
    port: 8002
    api_key: xxx
    device_id: xxx
    mac: XX:XX:XX:XX:XX
    source_list: '{"Ziggo": "ST_HDMI1", "Chromecast": "ST_HDMI3"}'
    app_list: '{"YouTube": "111299001912", "Netflix": "11101200001", "Plex": "3201512006963", "YouTube Kids": "3201611010983", "Videoland": "3201810017074"}'

***Version of hasamsungtv-tizen***
1.4.9

arch | x86_64
-- | --
chassis | desktop
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | Ubuntu 18.04.4 LTS
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 4.15.0-101-generic
python_version | 3.7.7
supervisor | 228
timezone | Europe/Amsterdam
version | 0.112.0
virtualenv | false

**Comment by jaruba** [comment]
That's strange.. Any errors / warnings in ur logs? have u made any changes to ur network? Have u tried changing the `update_method` to one of the other possible values?

**Comment by mike9011** [comment]
> That's strange.. Any errors / warnings in ur logs? have u made any changes to ur network? Have u tried changing the `update_method` to one of the other possible values?

No I haven't changed anything on my network. TV is connected with a cable and a static IP.
I just tried the other methods; websockets and smartthings but unfortunately didn't resolved the issue. I recreated the API key but didn't works either.

**Comment by mike9011** [comment]
Issue is resolved. Did a smartthings reset on my TV and connect the TV again.

**Comment by jaruba** [comment]
Uhm, did the chaotic On / Off states get resolved too? I'm seeing similar chaotic states on my 2 TVs also now.

**Comment by mike9011** [comment]
> Uhm, did the chaotic On / Off states get resolved too? (not only the app change issues)
> 
> I'm seeing similar chaotic states on my 2 TVs also now. How did u do the smart things reset?

Yes that's resolved too now! 

I have my TV set in the Dutch language so I'm not sure what the menus are named exactly in English;

Go to Settings > Support (last menu item, cloud as icon) > Self diagnose (2nd menu item) > Setup Smart Hub(5th menu item) 

It will remove all the apps and settings of the TV! After that I opened Smartthings on my phone, rebooted HA and the issues were resolved.

**Comment by jaruba** [comment]
Thanks for explaining, Smart Things has indeed pushed some weird changes lately, and there's logic in the code that sometimes relied on their state announcements if the config has the API setup. I might need to think of a way to make the states less reliant on their API.

**Comment by alex7614** [comment]
For me and for my 2 TV Q90, no need to reset Smart Hub.

I just started the Smarthings Apps on TV and after few seconds, everthing works again

**Comment by colethegamer123** [comment]
That solution worked for me too, after 3 month of using the component all the Apps are gone from the list. Now after readding to SmartThings, automaticly gathered all App name.
