### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by obaldius** [jaruba/ha-samsungtv-tizen#79]
hey, first of thanks for your component

I found this in my registry, I guess you'll know what it means:

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for samsungtv_tizen doing I/O at custom_components/samsungtv_tizen/upnp.py, line 28: response = requests.post("http://{host}:9197/upnp/control/{protocole}1".format(host=self.host, protocole=protocole), data=body, headers=headers, timeout=0.1)

**Comment by jaruba** [comment]
What version of HA are you using? Have you installed the latest version of this integration?

**Comment by obaldius** [comment]
0.111.4 and yes, the integration the latest version. I guess you suggest to uninstall and reinstall the integration again?

**Comment by jaruba** [comment]
no, i wasn't going to suggest that 😄

**Comment by obaldius** [comment]
oh ok, it shows up when I use the cast url service

**Comment by energywave** [comment]
I've read, some time ago, that HA made a change and requested all integration to respond in short times, forcing them to use async calls so that I/O is not done in the same thread as the requester. I've tried to find that note but I could not find it. Hope not to be wrong and to be inherent.

**Comment by obaldius** [comment]
it show up even when I call the homeassistant.turn_on service. TV won't turn on and it yields this error

**Comment by jaruba** [comment]
i think i fixed this with v1.5.0, reopen the issue if you still see that warning

**Comment by obaldius** [comment]
thanks a lot!I will
