### ISSUE TITLE
Get current channel number

### ISSUE THREAD

**Issue by Gamelauncher** [jaruba/ha-samsungtv-tizen#8]
First off great work! Plugin is working fine on both:
- QE55Q6FNA
- UE43RU7172

To make it complete besides the workaround for input switching, is there a way to get the current channel number?

**Comment by jaruba** [comment]
This seems very similar to https://github.com/jaruba/ha-samsungtv-custom/issues/9

But as I said there, I have no idea of how to get channel data yet, and I've done excessive research on whatever I could find from the available APIs.

**Comment by jaruba** [comment]
But we should be able to set channel names in source_list, and use key chaining to go through the tv menu and select the channel number.

That won't show us what channel is selected though..

**Comment by Gamelauncher** [comment]
Sending a channel number is already possible through HA native without the need for key chaining ...

Just having a way to find out what channel is on is the only thing missing I think :)

`
          - type: custom:button-card
            aspect_ratio: 1/1
            haptic: light
            tap_action:
              action: call-service
              service: script.channel_nr
              service_data:
                value: 156

channel_nr:
  alias: Channel nr
  sequence:
    - service: media_player.play_media
      data_template:
        entity_id: media_player.tv_living
        media_content_id: '{{value}}'
        media_content_type: "channel"
`

**Comment by jaruba** [comment]
Newest release includes the SmartThings API, you'll need to set `api_key` and `device_id` to enable it. The SmartThings API adds many new things, and also fixes this issue.
