### ISSUE TITLE
alphanumeric identifier

### ISSUE THREAD

**Issue by edwardtich1** [jaruba/ha-samsungtv-tizen#83]
How do I find an alphanumeric identifier?
On one TV there are many sources and on the other TV only TV in HDMI

**Comment by jaruba** [comment]
> a way finding the alphanumerical ID is by enabling the SmartThings API and running an app on the TV, this will show the alphanumerical ID as media_title in the component

from the app_list docs: https://github.com/jaruba/ha-samsungtv-tizen/blob/master/App_list.md

there is no other way that i know of to find them
