### ISSUE TITLE
Media title info

### ISSUE THREAD

**Issue by dreambeam** [jaruba/ha-samsungtv-tizen#9]
I wonder if there a way to pull out the media title? Does the tizenOS expose an api? Like when watching CNN  gather the following from the HA states api 
```
"media_title": "CNN"
```

**Comment by jaruba** [comment]
@dreambeam

That would obviously be cool, but I have no idea of how to get channel data, and I've done excessive research.

**Comment by jaruba** [comment]
But we should be able to set channel names in `source_list`, and use key chaining to go through the tv menu and select the channel number.

But it won't show us what channel is selected..

**Comment by jaruba** [comment]
Newest release includes the SmartThings API, you'll need to set `api_key` and `device_id` to enable it. The SmartThings API adds many new things, and also fixes this issue.
