### ISSUE TITLE
Delay between commands

### ISSUE THREAD

**Issue by prbtt** [jaruba/ha-samsungtv-tizen#95]
The update didn't solve the problem here unfortunately.
So, I build this Lovelace interface for controlling my TV and each arrow is a call-service: media_player.play_media which sends directional keys. There is still a 2 sec delay between each call-service.

![Screenshot_20201018-105342_Home Assistant](https://user-images.githubusercontent.com/60021461/96369457-6bd29f80-1130-11eb-9eee-e739f2b98b86.jpg)

**Comment by jaruba** [comment]
wait, did u try with key chaining in `media_playet.play_media`? (example: `KEY_1+KEY_5+KEY_2+KEY_ENTER`) or with ur lovelace card? (which sends one key at a time)

The initial issue was with key chaining, wasn't it? Maybe I understood it wrongly.

**Comment by prbtt** [comment]
> Wait, did u try with key chaining in `media_player.play_media`? (example: `KEY_1+KEY_5+KEY_2+KEY_ENTER`) or with ur lovelace card? (which sends one key at a time)
> 
> The initial issue was with key chaining, wasn't it? Maybe I understood it wrongly.

I wasn't using key chaining, but just sending media_player.play_media through my arrow keys in Lovelace. And I can't navigate in the menu smoothly because of this delay. I have to wait 2 seconds before I can send another directional key command.

**Comment by Screwdgeh** [comment]
@prbtt what hardware are you running home assistant on? And what version are you running? I tried on my end and it was actually very responsive to sending keys, I could press multiple times within a second and have it responding. Only few times the delay gets bigger for me it seems, but that feels like a similar consistency as an actual IR remote.

I run home assistant as a jail on a FreeNAS server though with a pretty capable CPU vs. e.g. a raspberry Pi. Currently running 0.114.3. I'm wondering if this makes a big difference...

By the way this looks really cool! Do you feel up to sharing this? I would love to give this a try!

**Comment by prbtt** [comment]
> @prbtt what hardware are you running home assistant on? And what version are you running? I tried on my end and it was actually very responsive to sending keys, I could press multiple times within a second and have it responding. Only few times the delay gets bigger for me it seems, but that feels like a similar consistency as an actual IR remote.
> 
> I run home assistant as a jail on a FreeNAS server though with a pretty capable CPU vs. e.g. a raspberry Pi. Currently running 0.114.3. I'm wondering if this makes a big difference...
> 
> By the way this looks really cool! Do you feel up to sharing this? I would love to give this a try!

I'm on a RPI 4b 4GB RAM, Operating system
HassOS 4.14, Supervisor
Version
247
Newest version
247
version | 0.116.4
`cards:
  - entities:
      - entity: input_select.input_tv_sala
      - label: Volume
        type: section
      - entity: media_player.samsung_tv_remote
        full_row: true
        hide_state: false
        icon: 'mdi:volume-source'
        name: Volume
        step: 1
        tap_action:
          action: none
        type: 'custom:slider-entity-row'
    type: entities
  - default_dismiss: false
    default_open: true
    icon: 'mdi:circle'
    items:
      - entity: light.pixar
        icon: 'mdi:arrow-up'
        tap_action:
          action: call-service
          service: script.tv_up
          service_data:
            entity_id: script.tv_up
      - entity: light.pixar
        icon: 'mdi:arrow-right'
        tap_action:
          action: call-service
          service: script.tv_right
          service_data:
            entity_id: script.tv_right
      - entity: light.pixar
        icon: 'mdi:arrow-down'
        tap_action:
          action: call-service
          service: script.tv_down
          service_data:
            entity_id: script.tv_down
      - entity: light.pixar
        icon: 'mdi:arrow-left'
        tap_action:
          action: call-service
          service: script.tv_left
          service_data:
            entity_id: script.tv_left
    tap_action:
      action: call-service
      service: media_player.play_media
      service_data:
        entity_id: media_player.samsung_tv_remote
        media_content_id: KEY_ENTER
        media_content_type: send_key
    type: 'custom:radial-menu'
  - default_dismiss: false
    default_open: true
    icon: 'mdi:home'
    items:
      - entity: light.pixar
        icon: 'mdi:nothing'
        tap_action:
          action: call-service
          haptic: false
          service: media_player.play_media
          service_data:
            entity_id: media_player.samsung_tv_remote
            media_content_id: KEY_UP
            media_content_type: send_key
      - entity: light.pixar
        hold_action:
          action: call-service
          service: media_player.turn_on
          service_data:
            entity_id: media_player.samsung_tv_remote
        icon: 'mdi:power'
        show_name: false
        size: 100%
        state:
          - color: green
            icon: 'mdi:power'
            show_name: false
            show_state: true
            value: 'on'
          - color: red
            icon: 'mdi:power'
            operator: default
            show_state: true
        styles:
          card:
            - width: 80px
            - height: 90px
            - '--paper-card-background-color': 'rgba(0, 0, 0, 0.0)'
            - box-shadow: none
        tap_action:
          action: call-service
          haptic: false
          service: media_player.toggle
          service_data:
            entity_id: media_player.samsung_tv_remote
      - entity: light.pixar
        icon: 'mdi:nothing'
        tap_action:
          action: call-service
          haptic: false
          service: media_player.play_media
          service_data:
            entity_id: media_player.samsung_tv_remote
            media_content_id: KEY_DOWN
            media_content_type: send_key
      - entity: light.pixar
        icon: 'mdi:keyboard-return'
        tap_action:
          action: call-service
          haptic: false
          service: media_player.play_media
          service_data:
            entity_id: media_player.samsung_tv_remote
            media_content_id: KEY_RETURN
            media_content_type: send_key
    tap_action:
      action: call-service
      service: media_player.play_media
      service_data:
        entity_id: media_player.samsung_tv_remote
        media_content_id: KEY_HOME
        media_content_type: send_key
    type: 'custom:radial-menu'
type: 'custom:vertical-stack-in-card'
`

**Comment by jaruba** [comment]
I'm on a RPI 3b+ (HA v0.116.4) and can also confirm a ~2s delay. I was also thinking that HA + hardware could influence this, but i'm not dismissing the fact that it might be an issue on our end as well. I know we use 2x `try/catch` in the `send_command` function. I also know that `try/catch` can indeed add quite some time to logic in many programming languages, but optimising the code is a time consuming task that would require a lot of debugging.. and in the end we might not be able to reduce the time significantly this way.

**Comment by jaruba** [comment]
I did some tests with all `try/catch` logic commented out and did not see any relevant improvement on the speed. Looking at the code I can't imagine how this could be component issue.. I'm inclined to believe that HA / hardware might actually influence the speed of this a lot..

When I started working on this component the commands were indeed sent much faster, although not much has changed in the code related to sending these keys since then, HA did change a lot since though..

**Comment by MysticMystic** [comment]
I had a similar issue if I understand it correctly this morning and took a look quick.  

I don't know where the delay is coming in, it is somewhere after the first command is run so suspect something around the update of the states that happen after each command, as the first command is immediate and then you get the delay for subsequent commands.  So the command is executed quickly then something happens...

I did see in mediaplayer.py line 884 it is specified with an await for any command key.  So i figured as it is just an update happening after that in the background let me take it out and my keys are very responsive now.

Haven't seen any unexpected issues yet. Image where I removed the await.

![image](https://user-images.githubusercontent.com/28574833/98098881-95612a00-1e97-11eb-9999-fd289bd3e8a1.png)

Not sure if this is helpful?

**Comment by jaruba** [comment]
TBH, my primary theory is that this has a lot to do with the websocket timeout:
https://github.com/jaruba/ha-samsungtv-tizen/blob/master/custom_components/samsungtv_tizen/websockets.py#L47

But I haven't tested this theory, it's just a hunch..

**Comment by profx5015** [comment]
got the same issue. is there some solution?

**Comment by jaruba** [comment]
@profx5015 Are u also using an RPI as ur HA device?

**Comment by jaruba** [comment]
I'm thinking of reverting my initial changes regarding this, I think they might break more then they fix in the long run..

**Comment by Philip-Hel** [comment]
I'm still running with my change I made where I let the command run asynchronously without waiting for the response.  Been working out great in how I use it, very responsive remote.  no issues yet, but I obviously am not using all the features.
I really see these commands when used as a remote as fire and forget, one way.

**Comment by jaruba** [comment]
@Philip-Hel 

I have nothing against ur solution, but that is related only to sending 1 key, which avoids the logic i added for key chaining... Where previously it would `await` keys, it now just throws them at the TV with a delay.. When initially tested, the delay was too short and it could skip some keys completely, which makes me feel like it's fragile logic... even though i couldn't reproduce it anymore with the last (higher) delay that was set.. maybe i should make the initial logic the default behaviour and add a setting to enable sending keys with a specific delay between them too..

Regardless, I'll make the change you proposed also.

**Comment by jaruba** [comment]
@Philip-Hel i made the change you proposed and published a new version (v1.5.5) if this problem persists we can reopen the issue.

**Comment by prbtt** [comment]
With Philip's modification my commands are now instant! Excellent, thank you very much!!
