### ISSUE TITLE
compatibile with THE FRAME 2020 QE55LS03TAUXZT

### ISSUE THREAD

**Issue by pilot1981** [jaruba/ha-samsungtv-tizen#96]
Hi,
I'm trying to integrate with THE FRAME 2020 QE55LS03TAUXZT, but I'm not able to have it working...

this is compatibile with THE FRAME 2020 QE55LS03TAUXZT?

can you help me?

**Comment by Screwdgeh** [comment]
Hi @pilot1981, expectation is it should work fine as it seems to run Tizen OS as any other smart TV.

Going to need more info to help. Can you share your configuration.yaml lines for the component and describe what is not working?

**Comment by pilot1981** [comment]
this is my config:

samsungtv:
  - host: 192.168.1.113
    turn_on_action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: "a4:30:7a:e7:7a:f0"

and this is the result:
<img width="395" alt="Schermata 2020-10-27 alle 15 11 55" src="https://user-images.githubusercontent.com/46350465/97313543-0afd4280-1867-11eb-82cc-df347d9480e5.png">

**Comment by Screwdgeh** [comment]
That configuration is not using the custom_component to which you are addressing your issue, but rather is using the standard 'samsungtv' component in home assistant.

Please follow instructions here to install the custom 'samsungtv-tizen' component to your home assistant: 
https://github.com/jaruba/ha-samsungtv-tizen/blob/master/README.md

**Comment by pilot1981** [comment]
it's also possibile to select directly a specific TV channel?

**Comment by Screwdgeh** [comment]
Yes, check out the documentation on the 'channel_list' option for the component. After configuration you will be able to select the tv channel via the UI from a drop down list as well as via a voice assistant if you have one of those (e.g. google assistant) enabled via home assistant. Other features including changing the volume, play/pause/mute/unmute and the input source to an app or hdmi output. 

If you have enabled the smartthings option you will also see the TV channel name as well a nice logo if it is in the database.

**Comment by pilot1981** [comment]
if I understood, my right config is this?

media_player:
  - platform: samsungtv_tizen
    host: 192.168.1.113
    mac: "a4:30:7a:e7:7a:f0"
    channel_list:

**Comment by jaruba** [comment]
@pilot1981 add `port: 8002` to that config, and `channel_list` must have a value, it can't be empty

**Comment by pilot1981** [comment]
where I can find value for channel_list?

**Comment by pilot1981** [comment]
I'm testing this integration but power on and power off features don't works....

**Comment by jaruba** [comment]
@pilot1981 

Read the docs carefully, it explains everything, for best results enable the SmartThings API in the component.

The power on / off doesn't work because of the frame tv, there is a different issue for that: https://github.com/jaruba/ha-samsungtv-tizen/issues/46

**Comment by pilot1981** [comment]
thanks, now all works fine!

regards

**Comment by jaruba** [comment]
@pilot1981 Does turn on / off also work for u on the frame tv? Curious as it shouldn't work according to other users.

**Comment by pilot1981** [comment]
work only power off, I'm waiting for fix of power on...
