### ISSUE TITLE
Casting videos to TV

### ISSUE THREAD

**Issue by obaldius** [jaruba/ha-samsungtv-tizen#97]
Not sure this is an issue, but I'm a noob and I dunno what the problem is.

I've been succesfully casting videos from a dlna server to my samsung tv using your custom component. It's been working great. Problem is I've had to give up the router where my dlna server was running. I've tried to cast images stored in the RPi sd card to my tv and it works, however when I try to cast those very same videos stored in the RPi sd card it yields and  error...

thanks in advanced, any help will be appreciated

**Comment by jaruba** [comment]
U say:
> I've tried to cast images stored in the RPi sd card to my tv and it works

After which u say:
> however when I try to cast those very same videos stored in the RPi sd card it yields and error...

These 2 things contradict themselves, show me the URL u are trying to cast, and also test it in ur browser too to see if it works there.

**Comment by jaruba** [comment]
Also keep in mind that ur TV does not support all video types, only some video types that the TV supports work to be casted.

**Comment by obaldius** [comment]
> Also keep in mind that ur TV does not support all video types, only some video types that the TV supports work to be casted.

I know but I was able to cast all these videos previously using and Asus router as a DLNA server. The service was able to cast them from there. Problem is when I copy those very same videos in the www folder. I have both images and videos stored in the same folder. Here you have the URLs:

image: 'http://192.168.5.102:8123/local/escudo_barcelon_2.jpg'

video: 'http://192.168.5.102:8123/local/earthbound.mp4'

When I cast the video, the loading circle animation keeps rolling for between 10-20 seconds and then yiels an error which says something like "file currently not supported". Images load instanty.

By the way, video loads instantly in the browser too.. Thanks in advanced for your help

**Comment by obaldius** [comment]
I want to cast some videos whitin some scenes I have created. It's been working beautifullly with your component, clean and quick. With Plex it gets ugly since the TV needs to launch the app (10-15 seconds).

Are you saying I would be able to launch videos stored in the www folder to the Plex app?

Thank you anyways!

**Comment by jaruba** [comment]
I don't use Plex, but as far as I know u can add videos to it's library, and it has a setting to enable a DLNA server with the contents of it's library.

**Comment by obaldius** [comment]
well, I'll see what I can do, thanks!

**Comment by jaruba** [comment]
Good luck with it. Keep in mind, this is a web server issue u are having, so IMO it should get fixed if u just run some DLNA server (it doesn't need to be Plex, it's just the one that came to mind) in ur HA setup.

**Comment by obaldius** [comment]
I don't mean to abuse your time but, I believe this is my last question. If I wanted to run a simple DLNA server in the very same RPi in which I have HA installed, which HA installation should I go with? I mean, I believe it's not possiblem to set a DLNA server in Hassio, which is my current instalation. Which should I be looking for?

thanks for everything, your cast service really works nice

**Comment by obaldius** [comment]
By the way, when I try to cast the video, in the HA logs the following error shows up. I can't understand a thing but probably you...

> Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 592, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 283, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 806, in state_attributes
    value = getattr(self, attr)
  File "/usr/src/homeassistant/homeassistant/components/dlna_dmr/media_player.py", line 284, in volume_level
    return self._device.volume_level
  File "/usr/local/lib/python3.8/site-packages/async_upnp_client/profiles/dlna.py", line 400, in volume_level
    return self._level('Volume')
  File "/usr/local/lib/python3.8/site-packages/async_upnp_client/profiles/dlna.py", line 303, in _level
    raise UpnpError('Missing StateVariable RC/%s' % (var_name, ))
async_upnp_client.client.UpnpError: Missing StateVariable RC/Volume

**Comment by jaruba** [comment]
That error seems unrelated, as far as I can tell it has not even related to this component.. Regarding your other questions of which HA installation / DLNA server, I can't offer assistance with that.

**Comment by obaldius** [comment]
well, thanks a lot for your time, have a good day
