### ISSUE TITLE
Unable to differentiate 2 different TV

### ISSUE THREAD

**Issue by marcodb82** [jaruba/ha-samsungtv-tizen#99]
If i add 2 TV like this:

media_player:
  - platform: samsungtv_tizen
    host: "192.168.1.11"
    mac: "xxxxxxxxxxx"
    #api_key: ""
    #device_id: ""
    #show_channel_number: true
  - platform: samsungtv_tizen
    host: "192.168.1.12"
    mac: "yyyyyyyyyyy"   

In my dashboard appear two PLAYER with the same name "SAMSUNG TV Remote"

How to selve?

thaks

**Comment by jaruba** [comment]
set a `name` of ur TVs in the config

**Comment by marcodb82** [comment]
tks,
why you not insert `name` variable , in Custom configuration variables of 
https://github.com/jaruba/ha-samsungtv-tizen
?

**Comment by jaruba** [comment]
i added it to the docs: https://github.com/jaruba/ha-samsungtv-tizen/commit/66f02050822eddb73f03876294ac6d5494c0d086
